apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  namespace: lgcns
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver-container
          image: 512138915880.dkr.ecr.us-east-2.amazonaws.com/configserver:latest
          ports:
          - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: configserver-service
  namespace: lgcns
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8888
  selector:
    app: configserver