spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://configserver-service:80"
  cloud:
    config:
      fail-fast: true
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowCredentials: false
      routes:
        - id: user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
          uri: http://user-service:80
        - id: product-service
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1
          uri: http://product-service:80
        - id: order-service
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
          uri: http://order-service:80

jwt:
  secret: jslim-super-secret-key-for-jwt-123456789